
resource "local_file" "save_users" {
  content = templatefile(
    "${path.cwd}/data/templates/credentials.tpl",
    # "./templates/users.tpl",
    {
      "trainers" = {
        for user in local.trainers : aws_iam_user.trainer[user].name => {
          "access" = aws_iam_access_key.trainer[user].id,
          "secret" = aws_iam_access_key.trainer[user].secret,
        }
      },
      "users" = {
        for user in local.users : aws_iam_user.user[user].name => {
          "access" = aws_iam_access_key.user[user].id,
          "secret" = aws_iam_access_key.user[user].secret,
        }
      }
    }
  )
  filename = "${path.cwd}/data/autogenerated/credentials.txt"
}
