
resource "local_file" "save_users" {
  content = templatefile(
    "${path.cwd}/data/templates/credentials.tpl",
    # "./templates/users.tpl",
    {
      "account" = local.target_account,
      "region"  = local.target_region,
      "trainers" = {
        for trainer in local.trainers : aws_iam_user.trainer[trainer].name => {
          "password" = random_password.trainer[trainer].result,
          "access"   = aws_iam_access_key.trainer[trainer].id,
          "secret"   = aws_iam_access_key.trainer[trainer].secret,
        }
      },
      "students" = {
        for student in local.students : aws_iam_user.student[student].name => {
          "password" = random_password.student[student].result,
          "access"   = aws_iam_access_key.student[student].id,
          "secret"   = aws_iam_access_key.student[student].secret,
        }
      }
    }
  )
  filename = "${path.cwd}/data/autogenerated/credentials.txt"
}
